### ISSUE TITLE
macOS whines about privileges/rights

### ISSUE THREAD

**Issue by robinvandernoord** [robinvandernoord/ZeroNetLauncher#1]
When you download the launcher and try to run it from downloads it might say the user does not have enough rights.

**Comment by BenjaminLawson** [comment]
This isn't a problem with the launcher, this is how macOS security settings are supposed to work.

The Fix: right-click ZeroNet.command and select "open". The dialogue  will now have the option to open the launcher.

Edit: After overcoming this issue, I found the real problem I think you are describing:
![screenshot_291](https://cloud.githubusercontent.com/assets/3166039/17642224/24c8d0fc-60f2-11e6-9f0b-80f6b076b74a.jpg)

Here's a stackoverflow thread resolving this issue:
http://apple.stackexchange.com/questions/113974/full-privileges-on-command-file-but-it-says-i-dont-have-appropriate-privilege

Summary:
Navigate to directory in Terminal and enter 

```
chmod u+x ./ZeroNet.command
```

**Comment by robinvandernoord** [comment]
@JordekFluffball Yeah that's the popup I meant. If a user has to `chmod` that defeats the entire purpose of this launcher. Do you know if chmod stays if you put it in a .zip? It doesn't stay if the user just downloads ZeroNet.command (on the original file I gave it the needed rights but when I uploaded and downloaded that file the privileges were gone)
